### PR TITLE
fix: 修复组件中使用wxs事件

### LINKED ISSUE #2068: wxs是不能在组件里用吗？
## Description
wxs是不能在组件里用吗？同一份wxs, 在page里可以正常使用, 在component就不行了,
看了编译后的index.wxml, 发现page的wxs标签是在第一行，而componet的wxs是在组件的上两行加入的
## Environment
  * wepy-cli version: 1.7.3
  * wepy version: ^1.6.0

## Relevant Code / Logs
`
// index.wpy
<template>
    <view class="container">
         <view style="width: 300px; height: 400px; background-color: red" @touchstart="{{e.event}}"></view>
         <cardstack></cardstack>
    </view>
</template>
<script>
import wepy from 'wepy'
import E from '../wxs/wxs.wxs'

export default class Index extends wepy.page{
    wxs = {
        e: E
    }
}
<
`
`
// CardStack.wpy
<template>
    <view style="width: 300px; height: 400px; background-color: blue" @tap="{{e.event}}">CardStack</view>
</template>
<script>
import wepy from 'wepy'
import E from '../wxs/wxs.wxs'

export default class CardStack extends wepy.component {
    wxs = {
        e: E
    }
}
</script>
`
`<wxs src="../wxs/wxs.wxs" module="e"/>

  <view class="container">
    <view style="width: 300px; height: 400px; background-color: red" bindtouchstart="{{e.event}}"/>
    <wxs src="../wxs/wxs.wxs" module="e"/>

    <view style="width: 300px; height: 400px; background-color: blue" bindtap="$cardstack${{e.event}}">CardStack</view>

  </view>
  `

### PR DESCRIPTION
**Pull request by sachielxsuo**
组件中使用wxs事件，会被当作组件变量编译成$parent$wxs这种形式，实际上这里不应该被处理

- 修复组件中使用wxs事件不生效的问题

Issue #2068
Close #2068

##### Checklist

- [x] `npm run test` passes

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/wepy?pullRequest=2144) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/wepy?pullRequest=2144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/wepy?pullRequest=2144) it.</sub>

File: packages/wepy-cli/src/compile-template.js [hunk 1]
```diff
@@ -311,7 +311,11 @@ export default {
                             node.setAttribute(paramAttr, p);
                         });
                     }
-                    if (prefix)
+
+                    let match = attr.value.match(/^\{\{\s*(\w+)(\.|\[).*\}\}$/);
```
Comment (Gcaufy) [inline packages/wepy-cli/src/compile-template.js]: why not to use attr.value.trim().startWith?

**Comment by Gcaufy** [comment]
多谢 PR, 抱歉这么晚处理。代码已评论
